# Makefile generated by Chat-GPT 3.5
# But modified a bit
# 16.12.2023

COL1  := \033[0;34m
COL2  := \033[0;35m
BOLD  := \033[1m
RESET := \033[0m

CC := gcc
CFLAGS := -Wall -Wextra -std=c99 -g
LDFLAGS := -lncurses -lm

SRCDIR := src
OBJDIR := obj
BINDIR := bin
INCDIR := include

SOURCES := $(wildcard $(SRCDIR)/*.c)
OBJECTS := $(patsubst $(SRCDIR)/%.c, $(OBJDIR)/%.o, $(SOURCES))
EXECUTABLE := $(BINDIR)/exanis

$(shell mkdir -p $(OBJDIR) $(BINDIR))

$(EXECUTABLE): $(OBJECTS)
	@echo "$(COL2)Linking all files into $(BOLD)$@$(RESET)"
	@$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

$(OBJDIR)/%.o: $(SRCDIR)/%.c
	@echo "$(COL1)Compiling $(BOLD)$<$(RESET)"
	@$(CC) $(CFLAGS) -I$(INCDIR) -c -o $@ $<

.PHONY: clean
clean:
	rm -f $(OBJECTS) $(EXECUTABLE)

